### ISSUE TITLE
Продумать сущности бизнес-логики

### ISSUE THREAD

**Issue by pema4** [nekoguys/game_competition#15]
## Проблема
Сейчас сущностей бизнес-логики нет - используются просто модели из MongoDB

## Идея
Так как бэкенд всё равно переписывается, можно подумать про модель предметной области.
Также возможно создание новых игр в будущем, для этого можно подготовить какую-то базу

Предлагаю такие сущности:

### `Game` – собственно, игра
Состоит из трёх частей:
* ключевые поля: ID игры, тип игры (для начала поддержать только конкуренцию)
* `props` – настройки игры, задаётся при создании, потом не меняется;
* `state` – состояние игры, может меняться;

Наполнение и `props`, и `state` зависит только от проводимой игры, может быть представлено JSON-ом.

### `UpdateRequest` – обновление `state` для какой-то игры
Игроки своими действиями обновляют состояние игры. Пример для конкуренции:
* команда решила произвести *N* товара в *M* раунде – в состоянии игры к истории производства товаров дописывается N 
* преподаватель написал сообщение в чат - это записывается в состояние игры
* преподаватель забанил игрока - это тоже записывается в состояние игры

### `UpdateResponse` – реакция игры на обновление своего `state`
Игровой сервер обновляет состояние игры и получает ответ –  `UpdateResponse`. Пример:
* игре пришло сообщение, что команда произвела *N* товара. Возможные ответы игры:
  * не ок, твоя команда уже отвечала в этом раунде
  * ты произвёл слишком много товара, поэтому обанкротился и выбыл из игры
  * ок, сохранено
  * ок, сохранено, это был последний ответ в раунде, начинаем новый
  * ок, сохранено, это был последний ответ в последнем раунде, можно заканчивать игру
* преподаватель написал сообщение в чат. Возможные ответы игры:
  * ок, для всех игроков пришло новое сообщение

## Мотивация

Получается событийная модель, которая хорошо ложится на реактивный бэкенд.
Взаимодействие клиента/сервера будет выглядеть так:
* фронтенд отправляет бэкенду запрос
* бэкенд проверяет роли игрока, транслирует запрос в обновления игры
* при обновлении игры бэкенд получает ответ
* полученный ответ транслируется в сообщения/ответы фронтенду

### Бонусы
* просто делать новые игры – новые контроллеры, таблицы в базе данных делать не обязательно
* все обновления можно сохранять - получится лог игры
* по логу игры можно полностью воссоздать игру или откатить её до какого-то состояния

**Comment by ChrisBenua** [comment]
Настройки могут меняться после создания игры(но только до начала игры)
